FROM node:18-alpine

WORKDIR /app

# Install dependencies needed for build
COPY package*.json ./
RUN npm install

# Copy application files
COPY . .

# Build application
RUN npm run build:frontend

# Final stage - nginx
FROM nginx:alpine
COPY --from=0 /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
